CREATE TABLE IF NOT EXISTS provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    contato VARCHAR(11) NOT NULL,
    document VARCHAR(15) NOT NULL,
    email VARCHAR(70) NOT NULL,
    data_criado TIMESTAMP,
    data_atualizacao TIMESTAMP,
    status VARCHAR(255),
    CONSTRAINT uk_provider_nome UNIQUE (nome),
    CONSTRAINT uk_provider_contato UNIQUE (contato),
    CONSTRAINT uk_provider_document UNIQUE (document),
    CONSTRAINT uk_provider_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS usuario (
    id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    data_criado TIMESTAMP,
    status VARCHAR(255),
    provider_id BIGINT,
    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_provider FOREIGN KEY (provider_id) REFERENCES provider (id)
);

CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket VARCHAR(255),
    razao VARCHAR(255),
    document VARCHAR(255),
    cep VARCHAR(255),
    logradouro VARCHAR(255),
    numero_endereco VARCHAR(255),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(255),
    fatura VARCHAR(255),
    usuario UUID NOT NULL,
    cancel_requested_by VARCHAR(255),
    provider BIGINT NOT NULL,
    date_created TIMESTAMP,
    date_finished TIMESTAMP,
    cancel_requested_at TIMESTAMP,
    type VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT fk_tickets_usuario FOREIGN KEY (usuario) REFERENCES usuario (id),
    CONSTRAINT fk_tickets_provider FOREIGN KEY (provider) REFERENCES provider (id)
);

CREATE TABLE IF NOT EXISTS did_available (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cn VARCHAR(2) NOT NULL,
    prefixo VARCHAR(4) NOT NULL,
    mcdu VARCHAR(4) NOT NULL,
    area VARCHAR(20) NOT NULL,
    uf_area VARCHAR(255),
    updated_at TIMESTAMP,
    upload_at TIMESTAMP,
    status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS customer(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao VARCHAR(255),
    document VARCHAR(255),
    type_document VARCHAR(5),
    cep VARCHAR(255),
    logradouro VARCHAR(255),
    numero_endereco VARCHAR(255),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(255),
    provider BIGINT NOT NULL,
    created_at TIMESTAMP,
    status VARCHAR(50),
    CONSTRAINT fk_provider FOREIGN KEY (provider) REFERENCES provider (id)
    );

CREATE TABLE IF NOT EXISTS did(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    did BIGINT NOT NULL,
    customer BIGINT NOT NULL,
    provider BIGINT NOT NULL,
    created_at TIMESTAMP,
    status VARCHAR(50),
    CONSTRAINT unique_did UNIQUE (did),
    CONSTRAINT fk_customer FOREIGN KEY (customer) REFERENCES customer (id),
    CONSTRAINT fk_provider FOREIGN KEY (provider) REFERENCES provider (id),
    CONSTRAINT fk_did FOREIGN KEY (did) REFERENCES did_available (id)
    );

CREATE TABLE IF NOT EXISTS portability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(255) NOT NULL,
    municipio VARCHAR(255) NOT NULL,
    cnl_municipo INTEGER NOT NULL,
    area_local VARCHAR(255) NOT NULL,
    cnl_are_local INTEGER NOT NULL,
    provider_id BIGINT NOT NULL,
    ticket_id BIGINT NOT NULL,
    data_agendamento VARCHAR(255),
    hora_agendamento VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT fk_portability_provider FOREIGN KEY (provider_id) REFERENCES provider (id),
    CONSTRAINT fk_portability_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

CREATE SEQUENCE IF NOT EXISTS operators_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS operators (
    id BIGINT NOT NULL DEFAULT nextval('operators_seq'),
    nome_prestadora VARCHAR(255),
    cnpj_prestadora VARCHAR(255),
    uf VARCHAR(255),
    codigo_nacional VARCHAR(255),
    prefixo VARCHAR(255),
    faixa_inicial VARCHAR(255),
    faixa_final VARCHAR(255),
    codigo_cnl INTEGER,
    nome_localidade VARCHAR(255),
    area_local VARCHAR(255),
    sigla_area_local VARCHAR(255),
    codigo_area INTEGER,
    status VARCHAR(255),
    CONSTRAINT pk_operators PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_provider_id ON usuario (provider_id);
CREATE INDEX IF NOT EXISTS idx_tickets_usuario ON tickets (usuario);
CREATE INDEX IF NOT EXISTS idx_tickets_provider ON tickets (provider);
CREATE INDEX IF NOT EXISTS idx_customer_provider_id ON customer (provider);
CREATE INDEX IF NOT EXISTS idx_portability_ticket_id ON portability (ticket_id);
CREATE INDEX IF NOT EXISTS idx_portability_provider_id ON portability (provider_id);
