CREATE TABLE IF NOT EXISTS provedor (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    contato VARCHAR(11) NOT NULL,
    documento VARCHAR(15) NOT NULL,
    email VARCHAR(70) NOT NULL,
    data_criado TIMESTAMP,
    data_atualizacao TIMESTAMP,
    status_number VARCHAR(255),
    CONSTRAINT uk_provedor_nome UNIQUE (nome),
    CONSTRAINT uk_provedor_contato UNIQUE (contato),
    CONSTRAINT uk_provedor_documento UNIQUE (documento),
    CONSTRAINT uk_provedor_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS usuario (
    id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    data_criado TIMESTAMP,
    status_number VARCHAR(255),
    provedor_id INTEGER,
    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_provedor FOREIGN KEY (provedor_id) REFERENCES provedor (id)
);

CREATE TABLE IF NOT EXISTS tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket VARCHAR(255),
    razao VARCHAR(255),
    documento VARCHAR(255),
    cep VARCHAR(255),
    logradouro VARCHAR(255),
    numero_endereco VARCHAR(255),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(255),
    fatura VARCHAR(255),
    usuario UUID NOT NULL,
    provedor INTEGER NOT NULL,
    date_created TIMESTAMP,
    date_finished TIMESTAMP,
    type VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT fk_tickets_usuario FOREIGN KEY (usuario) REFERENCES usuario (id),
    CONSTRAINT fk_tickets_provedor FOREIGN KEY (provedor) REFERENCES provedor (id)
);

CREATE TABLE IF NOT EXISTS numbers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cn VARCHAR(2) NOT NULL,
    prefixo VARCHAR(4) NOT NULL,
    mcdu VARCHAR(4) NOT NULL,
    area VARCHAR(20) NOT NULL,
    uf_area VARCHAR(255),
    date_created TIMESTAMP,
    date_finished TIMESTAMP,
    data_upload TIMESTAMP,
    ticket_id INTEGER NOT NULL,
    provedor_id INTEGER NOT NULL,
    status_number VARCHAR(255),
    CONSTRAINT fk_numbers_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT fk_numbers_provedor FOREIGN KEY (provedor_id) REFERENCES provedor (id)
);

CREATE TABLE IF NOT EXISTS portability (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(255) NOT NULL,
    municipio VARCHAR(255) NOT NULL,
    cnl_municipo INTEGER NOT NULL,
    area_local VARCHAR(255) NOT NULL,
    cnl_are_local INTEGER NOT NULL,
    provedor_id INTEGER NOT NULL,
    ticket_id INTEGER NOT NULL,
    data_agendamento VARCHAR(255),
    hora_agendamento VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT fk_portability_provedor FOREIGN KEY (provedor_id) REFERENCES provedor (id),
    CONSTRAINT fk_portability_ticket FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

CREATE SEQUENCE IF NOT EXISTS operadoras_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS operadoras (
    id INTEGER NOT NULL DEFAULT nextval('operadoras_seq'),
    nome_prestadora VARCHAR(255),
    cnpj_prestadora VARCHAR(255),
    uf VARCHAR(255),
    codigo_nacional VARCHAR(255),
    prefixo VARCHAR(255),
    faixa_inicial VARCHAR(255),
    faixa_final VARCHAR(255),
    codigo_cnl INTEGER,
    nome_localidade VARCHAR(255),
    area_local VARCHAR(255),
    sigla_area_local VARCHAR(255),
    codigo_area INTEGER,
    status VARCHAR(255),
    CONSTRAINT pk_operadoras PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_provedor_id ON usuario (provedor_id);
CREATE INDEX IF NOT EXISTS idx_tickets_usuario ON tickets (usuario);
CREATE INDEX IF NOT EXISTS idx_tickets_provedor ON tickets (provedor);
CREATE INDEX IF NOT EXISTS idx_numbers_ticket_id ON numbers (ticket_id);
CREATE INDEX IF NOT EXISTS idx_numbers_provedor_id ON numbers (provedor_id);
CREATE INDEX IF NOT EXISTS idx_portability_ticket_id ON portability (ticket_id);
CREATE INDEX IF NOT EXISTS idx_portability_provedor_id ON portability (provedor_id);
